### PR TITLE
GmsCore update

### PR DESCRIPTION
**Pull request by slaip**
A new version of GmsCore has been released
https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.7.17455

### CODE REVIEW

**Comment by hieutvan** [comment]
Well, is it really needed to update GmsCore? As I see, you can just install the current version of the module, then update GmsCore by yourself.
The main purpose of the module is to install GmsCore, keeping it updated is totally up to the users :wink: Moreover, sometimes the latest version of Core is buggy

**Comment by abdulocracy** [comment]
I have been unable to update the core with the APK due to differences with the signature, either way the core has constant improvements in stability and compatibility with new versions of Android. I think this should be reconsidered.

**Comment by hieutvan** [comment]
> I have been unable to update the core with the APK due to differences with the signature, either way the core has constant improvements in stability and compatibility with new versions of Android. I think this should be reconsidered.

I'm my own, unmodified module and I can perfectly update it. By which channel did you update? Do you use microG's official F-Droid repo?

**Comment by hieutvan** [comment]
Sorry guys, I confirm that the signature mismatch problem is present. I will fix it soon

**Comment by nift4** [comment]
For refernce: fixed.

**Pull request closed without merging**
