### PR TITLE
Add GsfProxy

### PR DESCRIPTION
**Pull request by nift4**
Includes #5. DO NOT MERGE BOTH. Adds GsfProxy because this needs to be an system app for some apps to work and because the self-test recommends it.

### CODE REVIEW

**Comment by nift4** [comment]
@hieutvan

**Comment by hieutvan** [comment]
GsfProxy as system app? Self-check recommends it? I don't see anywhere that it say so. Can you clarify?

**Comment by nift4** [comment]
No, the self-check does not say that it should be an system app. It says that the GsfProxy is recommened. This installer would be (except Play Store) the all-round carefree package and some apps needs to habe GSF an system app.

**Comment by hieutvan** [comment]
Nice work

**Comment by hieutvan** [comment]
Hey @nift4 , did you include this fix too?

https://github.com/microg/android_packages_apps_GmsCore/issues/366#issuecomment-427252345

**Comment by nift4** [comment]
No, It worked for me on Pie. ASAP I had installed the propertary Play Services before. I you want you can fix it yourself, Simply add the permissions in the XML, or I can do it for you, simply say if.

**Comment by nift4** [comment]
Did it #7

**Pull request merged**
